In [1]:
from sklearn.cluster import KMeans
import numpy as np
import pandas as pd

In [2]:
#X = np.array([[1, 2], [1, 4], [1, 0],
#[10, 2], [1, 4], [10, 0]]) ## testing

In [3]:
#kmeans = KMeans(n_clusters=3, random_state=0).fit(X)

In [4]:
#kmeans.labels_

array([0, 2, 0, 1, 2, 1], dtype=int32)

In [49]:
## Here we have two cities LA and NY which can be changed but we will use this in my example
# My program intends to help a user decide which city is better to move to based on the food, entertainment,
# and shopping experience.
# A new city will be inputted and my program will cluster that new city to be more similar to LA or NY in this example.
## LA 34.0481° N, -118.2628° W Staples Center
## NY 40.7128° N, 74.0060° W Times Square
## Mtv View Downtown 37.389031, -122.082848 
# Enter 3 Coordinates of Cities you have been to and know well
g = input("Enter City 1 : (Format = Latitude, Longitude)") 


Enter City 1 : (Format = Latitude, Longitude)34.0481, -118.2628


In [45]:
g2 = input("Enter City 2 : (Format = Latitude, Longitude)") 


Enter City 2 : (Format = Latitude, Longitude)40.757344, -73.985456


In [41]:
g3 = input("Enter City 3 : (Format = Latitude, Longitude)") 

Enter City 3 : (Format = Latitude, Longitude)37.389031, -122.082848


In [46]:
g3

'37.389031, -122.082848'

In [47]:
X = np.array([[0,0,0,0], [0, 0, 0, 0], [0,0,0,0]])
X

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [50]:
### THE NEXT 8 BLOCKS OF THE NOTEBOOK ARE ME PULLING DATA FROM THE FOURSQUARE API
# I AM GETTING INFO ABOUT THE CITY
# Such as the entertainment and food
import json, requests
url = 'https://api.foursquare.com/v2/venues/search'
loc_list = [g,g2,g3]
stats = ["coffee","grocery","entertainment", "food"]
city_num = 0
index = 0
for j in loc_list:
    for i in stats:
        params = dict(
        client_id='ADRDGSC2UTF3DZTQHPTEYBRHCEISJAAC041OXNURITQEEVIB',
        client_secret='5XEV1NU0UBZFRZ5F0EM5KHGUHYFFD3UNJBKXDOE2WVUMCONP',
        v='20180323',
        ll= j, #change city location
        query=i,
        radius = '1500',
        limit = '50'
        )
        resp = requests.get(url=url, params=params)
        data = json.loads(resp.text)
        X[city_num,index] = len(data["response"]["venues"])
        index += 1
    index = 0
    city_num += 1
X

array([[50,  4, 29, 50],
       [50, 50, 50, 50],
       [15,  1,  0, 14]])

In [52]:
# I train my model based on the two cities that are to be compared to, NY and LA
kmeans = KMeans(n_clusters=3, random_state=0).fit(X)


In [61]:
kmeans.labels_
# 0 means it is more like LA
# 2 means it is more like NY
# 1 means it is more like MtvView

array([0, 2, 1], dtype=int32)

In [54]:
#San Jose 37.334708, -121.891474
g4 = input("Enter A City You Would Like To Compare To: (Format = Latitude, Longitude)") 

Enter A City You Would Like To Compare To: (Format = Latitude, Longitude)37.334708, -121.891474


In [59]:
stats = ["coffee","grocery","entertainment", "food"]
cityToBeMatchedStats = np.array([[0,0,0,0]])
index = 0
for i in stats:        
    params = dict(
    client_id='ADRDGSC2UTF3DZTQHPTEYBRHCEISJAAC041OXNURITQEEVIB',
    client_secret='5XEV1NU0UBZFRZ5F0EM5KHGUHYFFD3UNJBKXDOE2WVUMCONP',
    v='20180323',
    ll= g4, #change city location
    query=i,
    radius = '1500',
    limit = '50'
    )
    resp = requests.get(url=url, params=params)
    data = json.loads(resp.text)
    cityToBeMatchedStats[0,index] = len(data["response"]["venues"])
    index += 1
cityToBeMatchedStats

array([[36,  5,  0, 36]])

In [62]:
kmeans.predict(cityToBeMatchedStats)
#San Jose is most like MtvView

array([1], dtype=int32)