In [150]:
from sklearn.cluster import KMeans
import numpy as np
import pandas as pd

In [151]:
X = np.array([[1, 2], [1, 4], [1, 0],
[10, 2], [1, 4], [10, 0]]) ## testing

In [152]:
kmeans = KMeans(n_clusters=3, random_state=0).fit(X)

In [153]:
kmeans.labels_

array([0, 2, 0, 1, 2, 1], dtype=int32)

In [154]:
## Here we have two cities LA and NY which can be changed but we will use this in my example
# My program intends to help a user decide which city is better to move to based on the food, entertainment,
# and shopping experience.
# A new city will be inputted and my program will cluster that new city to be more similar to LA or NY in this example.
## LA 34.0481° N, -118.2628° W
## NY 40.7128° N, 74.0060° W



In [155]:
### THE NEXT 8 BLOCKS OF THE NOTEBOOK ARE ME PULLING DATA FROM THE FOURSQUARE API
# I AM GETTING INFO ABOUT THE CITY
# Such as the entertainment and food
import json, requests
url = 'https://api.foursquare.com/v2/venues/search'

params = dict(
client_id='ADRDGSC2UTF3DZTQHPTEYBRHCEISJAAC041OXNURITQEEVIB',
client_secret='5XEV1NU0UBZFRZ5F0EM5KHGUHYFFD3UNJBKXDOE2WVUMCONP',
v='20180323',
ll='34.0481, -118.2628', #change city location
query='coffee',
radius = '1000',
)
resp = requests.get(url=url, params=params)
data = json.loads(resp.text)
coffeenum = len(data["response"]["venues"])

In [156]:
params = dict(
client_id='ADRDGSC2UTF3DZTQHPTEYBRHCEISJAAC041OXNURITQEEVIB',
client_secret='5XEV1NU0UBZFRZ5F0EM5KHGUHYFFD3UNJBKXDOE2WVUMCONP',
v='20180323',
ll='34.0481, -118.2628', #change city location
query='grocery',
radius = '1000',
)
resp = requests.get(url=url, params=params)
data = json.loads(resp.text)
grocerynum = len(data["response"]["venues"])

In [157]:
params = dict(
client_id='ADRDGSC2UTF3DZTQHPTEYBRHCEISJAAC041OXNURITQEEVIB',
client_secret='5XEV1NU0UBZFRZ5F0EM5KHGUHYFFD3UNJBKXDOE2WVUMCONP',
v='20180323',
ll='34.0481, -118.2628', #change city location
query='entertainment',
radius = '1000',
)
resp = requests.get(url=url, params=params)
data = json.loads(resp.text)
funnum = len(data["response"]["venues"])

In [158]:
d = {'la': [coffeenum, grocerynum, funnum]}

X = np.array([[coffeenum, grocerynum, funnum], [0, 0, 0]])
X


array([[30,  4, 22],
       [ 0,  0,  0]])

In [159]:
#X[1,0] = coffeenum
#X

In [160]:
params = dict(
client_id='ADRDGSC2UTF3DZTQHPTEYBRHCEISJAAC041OXNURITQEEVIB',
client_secret='5XEV1NU0UBZFRZ5F0EM5KHGUHYFFD3UNJBKXDOE2WVUMCONP',
v='20180323',
ll='40.7088, -74.0126', #change city location
query='coffee',
radius = '1000',
)
resp = requests.get(url=url, params=params)
data = json.loads(resp.text)
coffeenum = len(data["response"]["venues"])
coffeenum

30

In [161]:
params = dict(
client_id='ADRDGSC2UTF3DZTQHPTEYBRHCEISJAAC041OXNURITQEEVIB',
client_secret='5XEV1NU0UBZFRZ5F0EM5KHGUHYFFD3UNJBKXDOE2WVUMCONP',
v='20180323',
ll='40.7128, 74.0060', #change city location
query='grocery',
radius = '1000',
)
resp = requests.get(url=url, params=params)
data = json.loads(resp.text)
grocerynum = len(data["response"]["venues"])
grocerynum

0

In [162]:
params = dict(
client_id='ADRDGSC2UTF3DZTQHPTEYBRHCEISJAAC041OXNURITQEEVIB',
client_secret='5XEV1NU0UBZFRZ5F0EM5KHGUHYFFD3UNJBKXDOE2WVUMCONP',
v='20180323',
ll='40.7128, 74.0060', #change city location
query='entertainment',
radius = '1000',
)
resp = requests.get(url=url, params=params)
data = json.loads(resp.text)
funnum = len(data["response"]["venues"])
funnum

0

In [163]:
X[1,0] = coffeenum
X[1,1] = grocerynum
X[1,2] = funnum
X

array([[30,  4, 22],
       [30,  0,  0]])

In [164]:
# I train my model based on the two cities that are to be compared to, NY and LA
kmeans = KMeans(n_clusters=2, random_state=0).fit(X)


In [165]:
kmeans.labels_
# 0 means it is more like LA
# 1 means it is more like NY

array([0, 1], dtype=int32)

In [166]:
#test_set = {'test': [30, 4, 22]}
#test_set = pd.DataFrame(data = test_set)
array = np.array([[30,4,22], [30,0,9]])
kmeans.predict(array)
# The first city is more like LA and the second is more like NY

array([0, 1], dtype=int32)